# Generated by Django 5.2.7 on 2025-11-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.TextField(blank=True),
        ),
    ]
